# Generated by Django 5.0.2 on 2024-04-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (
                    ("can_mark_returned", "Set book as returned"),
                    ("view_borrowed", "View all books borrowed"),
                ),
            },
        ),
    ]
